[package]
name = "aurora"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aurora"
path = "src/main.rs"

[[bin]]
name = "aurora_gui"
path = "src/aurora_gui.rs"

[dependencies]
eframe  = "0.27"
egui    = "0.27"
serde   = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
# build.rs nie wymaga zewnętrznych zależności