; AUTO GENERATED GRAMMAR KEYWORDS
; Słowa funkcyjne podzielone na kategorie

; === DETERMINERS ===
KW_DETERMINERS_START EQU 1
KW_DETERMINERS_COUNT EQU 20
KW_THE EQU 1  ; DETERMINERS
KW_A EQU 2  ; DETERMINERS
KW_AN EQU 3  ; DETERMINERS
KW_THIS EQU 4  ; DETERMINERS
KW_THAT EQU 5  ; DETERMINERS
KW_THESE EQU 6  ; DETERMINERS
KW_THOSE EQU 7  ; DETERMINERS
KW_MY EQU 8  ; DETERMINERS
KW_YOUR EQU 9  ; DETERMINERS
KW_HIS EQU 10  ; DETERMINERS
KW_HER EQU 11  ; DETERMINERS
KW_ITS EQU 12  ; DETERMINERS
KW_OUR EQU 13  ; DETERMINERS
KW_THEIR EQU 14  ; DETERMINERS
KW_SOME EQU 15  ; DETERMINERS
KW_ANY EQU 16  ; DETERMINERS
KW_NO EQU 17  ; DETERMINERS
KW_EACH EQU 18  ; DETERMINERS
KW_EVERY EQU 19  ; DETERMINERS
KW_EITHER EQU 20  ; DETERMINERS

; === PRONOUNS ===
KW_PRONOUNS_START EQU 21
KW_PRONOUNS_COUNT EQU 20
KW_I EQU 21  ; PRONOUNS
KW_YOU EQU 22  ; PRONOUNS
KW_HE EQU 23  ; PRONOUNS
KW_SHE EQU 24  ; PRONOUNS
KW_IT EQU 25  ; PRONOUNS
KW_WE EQU 26  ; PRONOUNS
KW_THEY EQU 27  ; PRONOUNS
KW_ME EQU 28  ; PRONOUNS
KW_HIM EQU 29  ; PRONOUNS
KW_HER_PRN EQU 30  ; PRONOUNS
KW_US EQU 31  ; PRONOUNS
KW_THEM EQU 32  ; PRONOUNS
KW_MYSELF EQU 33  ; PRONOUNS
KW_YOURSELF EQU 34  ; PRONOUNS
KW_HIMSELF EQU 35  ; PRONOUNS
KW_HERSELF EQU 36  ; PRONOUNS
KW_WHO EQU 37  ; PRONOUNS
KW_WHAT EQU 38  ; PRONOUNS
KW_WHICH EQU 39  ; PRONOUNS
KW_THAT_PRN EQU 40  ; PRONOUNS

; === CONJUNCTIONS ===
KW_CONJUNCTIONS_START EQU 41
KW_CONJUNCTIONS_COUNT EQU 17
KW_AND EQU 41  ; CONJUNCTIONS
KW_OR EQU 42  ; CONJUNCTIONS
KW_BUT EQU 43  ; CONJUNCTIONS
KW_NOR EQU 44  ; CONJUNCTIONS
KW_FOR EQU 45  ; CONJUNCTIONS
KW_YET EQU 46  ; CONJUNCTIONS
KW_SO EQU 47  ; CONJUNCTIONS
KW_BECAUSE EQU 48  ; CONJUNCTIONS
KW_ALTHOUGH EQU 49  ; CONJUNCTIONS
KW_WHILE EQU 50  ; CONJUNCTIONS
KW_WHEN EQU 51  ; CONJUNCTIONS
KW_IF EQU 52  ; CONJUNCTIONS
KW_UNLESS EQU 53  ; CONJUNCTIONS
KW_UNTIL EQU 54  ; CONJUNCTIONS
KW_SINCE EQU 55  ; CONJUNCTIONS
KW_AFTER EQU 56  ; CONJUNCTIONS
KW_BEFORE EQU 57  ; CONJUNCTIONS

; === PREPOSITIONS ===
KW_PREPOSITIONS_START EQU 58
KW_PREPOSITIONS_COUNT EQU 22
KW_IN EQU 58  ; PREPOSITIONS
KW_ON EQU 59  ; PREPOSITIONS
KW_AT EQU 60  ; PREPOSITIONS
KW_TO EQU 61  ; PREPOSITIONS
KW_FOR EQU 62  ; PREPOSITIONS
KW_WITH EQU 63  ; PREPOSITIONS
KW_BY EQU 64  ; PREPOSITIONS
KW_FROM EQU 65  ; PREPOSITIONS
KW_OF EQU 66  ; PREPOSITIONS
KW_ABOUT EQU 67  ; PREPOSITIONS
KW_THROUGH EQU 68  ; PREPOSITIONS
KW_BETWEEN EQU 69  ; PREPOSITIONS
KW_UNDER EQU 70  ; PREPOSITIONS
KW_OVER EQU 71  ; PREPOSITIONS
KW_AFTER EQU 72  ; PREPOSITIONS
KW_BEFORE EQU 73  ; PREPOSITIONS
KW_DURING EQU 74  ; PREPOSITIONS
KW_INTO EQU 75  ; PREPOSITIONS
KW_ONTO EQU 76  ; PREPOSITIONS
KW_WITHIN EQU 77  ; PREPOSITIONS
KW_WITHOUT EQU 78  ; PREPOSITIONS
KW_AGAINST EQU 79  ; PREPOSITIONS

; === MODALS ===
KW_MODALS_START EQU 80
KW_MODALS_COUNT EQU 12
KW_CAN EQU 80  ; MODALS
KW_COULD EQU 81  ; MODALS
KW_WILL EQU 82  ; MODALS
KW_WOULD EQU 83  ; MODALS
KW_SHALL EQU 84  ; MODALS
KW_SHOULD EQU 85  ; MODALS
KW_MAY EQU 86  ; MODALS
KW_MIGHT EQU 87  ; MODALS
KW_MUST EQU 88  ; MODALS
KW_OUGHT EQU 89  ; MODALS
KW_NEED_MOD EQU 90  ; MODALS
KW_DARE EQU 91  ; MODALS

; === AUXILIARIES ===
KW_AUXILIARIES_START EQU 92
KW_AUXILIARIES_COUNT EQU 13
KW_IS EQU 92  ; AUXILIARIES
KW_ARE EQU 93  ; AUXILIARIES
KW_WAS EQU 94  ; AUXILIARIES
KW_WERE EQU 95  ; AUXILIARIES
KW_BE EQU 96  ; AUXILIARIES
KW_BEEN EQU 97  ; AUXILIARIES
KW_BEING EQU 98  ; AUXILIARIES
KW_HAS EQU 99  ; AUXILIARIES
KW_HAVE EQU 100  ; AUXILIARIES
KW_HAD EQU 101  ; AUXILIARIES
KW_DO EQU 102  ; AUXILIARIES
KW_DOES EQU 103  ; AUXILIARIES
KW_DID EQU 104  ; AUXILIARIES

; === ADVERBS_PLACE ===
KW_ADVERBS_PLACE_START EQU 105
KW_ADVERBS_PLACE_COUNT EQU 9
KW_HERE EQU 105  ; ADVERBS_PLACE
KW_THERE EQU 106  ; ADVERBS_PLACE
KW_EVERYWHERE EQU 107  ; ADVERBS_PLACE
KW_NOWHERE EQU 108  ; ADVERBS_PLACE
KW_SOMEWHERE EQU 109  ; ADVERBS_PLACE
KW_INSIDE EQU 110  ; ADVERBS_PLACE
KW_OUTSIDE EQU 111  ; ADVERBS_PLACE
KW_NEARBY EQU 112  ; ADVERBS_PLACE
KW_AWAY EQU 113  ; ADVERBS_PLACE

; === ADVERBS_TIME ===
KW_ADVERBS_TIME_START EQU 114
KW_ADVERBS_TIME_COUNT EQU 15
KW_NOW EQU 114  ; ADVERBS_TIME
KW_THEN EQU 115  ; ADVERBS_TIME
KW_TODAY EQU 116  ; ADVERBS_TIME
KW_YESTERDAY EQU 117  ; ADVERBS_TIME
KW_TOMORROW EQU 118  ; ADVERBS_TIME
KW_ALWAYS EQU 119  ; ADVERBS_TIME
KW_NEVER EQU 120  ; ADVERBS_TIME
KW_OFTEN EQU 121  ; ADVERBS_TIME
KW_SOMETIMES EQU 122  ; ADVERBS_TIME
KW_USUALLY EQU 123  ; ADVERBS_TIME
KW_ALREADY EQU 124  ; ADVERBS_TIME
KW_STILL EQU 125  ; ADVERBS_TIME
KW_YET_ADV EQU 126  ; ADVERBS_TIME
KW_SOON EQU 127  ; ADVERBS_TIME
KW_RECENTLY EQU 128  ; ADVERBS_TIME

