; AUTO GENERATED CFG GRAMMAR RULES
; Format: RULE_<NAZWA>_LHS EQU <category_id>
;         RULE_<NAZWA>_LEN EQU <liczba_symboli>
;         RULE_<NAZWA>_0   EQU <pos_id_0>
;         RULE_<NAZWA>_1   EQU <pos_id_1>  ...

; Kategorie: 1=S 2=NP 3=VP 4=PP 5=ADJP 6=ADVP
; POS IDs:   1=N 2=V 3=ADJ 4=ADV 5=PRN 6=PRP
;            7=CNJ 11=DET 16=AUX 17=MOD 18=V_PAST 19=S

; --- S_BASIC: S -> NP VP ---
RULE_S_BASIC_LHS EQU 1
RULE_S_BASIC_LEN EQU 2
RULE_S_BASIC_0   EQU 0  ; NP
RULE_S_BASIC_1   EQU 0  ; VP

; --- S_QUESTION: S -> AUX NP VP ---
RULE_S_QUESTION_LHS EQU 1
RULE_S_QUESTION_LEN EQU 3
RULE_S_QUESTION_0   EQU 16  ; AUX
RULE_S_QUESTION_1   EQU 0  ; NP
RULE_S_QUESTION_2   EQU 0  ; VP

; --- S_PASSIVE: S -> NP AUX V_PAST PRP NP ---
RULE_S_PASSIVE_LHS EQU 1
RULE_S_PASSIVE_LEN EQU 5
RULE_S_PASSIVE_0   EQU 0  ; NP
RULE_S_PASSIVE_1   EQU 16  ; AUX
RULE_S_PASSIVE_2   EQU 18  ; V_PAST
RULE_S_PASSIVE_3   EQU 6  ; PRP
RULE_S_PASSIVE_4   EQU 0  ; NP

; --- S_COMPOUND: S -> S CNJ S ---
RULE_S_COMPOUND_LHS EQU 1
RULE_S_COMPOUND_LEN EQU 3
RULE_S_COMPOUND_0   EQU 19  ; S
RULE_S_COMPOUND_1   EQU 7  ; CNJ
RULE_S_COMPOUND_2   EQU 19  ; S

; --- NP_FULL: NP -> DET ADJ N ---
RULE_NP_FULL_LHS EQU 2
RULE_NP_FULL_LEN EQU 3
RULE_NP_FULL_0   EQU 11  ; DET
RULE_NP_FULL_1   EQU 3  ; ADJ
RULE_NP_FULL_2   EQU 1  ; N

; --- NP_SIMPLE: NP -> DET N ---
RULE_NP_SIMPLE_LHS EQU 2
RULE_NP_SIMPLE_LEN EQU 2
RULE_NP_SIMPLE_0   EQU 11  ; DET
RULE_NP_SIMPLE_1   EQU 1  ; N

; --- NP_BARE: NP -> N ---
RULE_NP_BARE_LHS EQU 2
RULE_NP_BARE_LEN EQU 1
RULE_NP_BARE_0   EQU 1  ; N

; --- NP_PRONOUN: NP -> PRN ---
RULE_NP_PRONOUN_LHS EQU 2
RULE_NP_PRONOUN_LEN EQU 1
RULE_NP_PRONOUN_0   EQU 5  ; PRN

; --- NP_PROPER: NP -> NP_NAME ---
RULE_NP_PROPER_LHS EQU 2
RULE_NP_PROPER_LEN EQU 1
RULE_NP_PROPER_0   EQU 10  ; NP_NAME

; --- NP_PREP: NP -> NP PP ---
RULE_NP_PREP_LHS EQU 2
RULE_NP_PREP_LEN EQU 2
RULE_NP_PREP_0   EQU 0  ; NP
RULE_NP_PREP_1   EQU 0  ; PP

; --- NP_MULTI_ADJ: NP -> DET ADJ ADJ N ---
RULE_NP_MULTI_ADJ_LHS EQU 2
RULE_NP_MULTI_ADJ_LEN EQU 4
RULE_NP_MULTI_ADJ_0   EQU 11  ; DET
RULE_NP_MULTI_ADJ_1   EQU 3  ; ADJ
RULE_NP_MULTI_ADJ_2   EQU 3  ; ADJ
RULE_NP_MULTI_ADJ_3   EQU 1  ; N

; --- VP_TRANS: VP -> V NP ---
RULE_VP_TRANS_LHS EQU 3
RULE_VP_TRANS_LEN EQU 2
RULE_VP_TRANS_0   EQU 2  ; V
RULE_VP_TRANS_1   EQU 0  ; NP

; --- VP_INTRANS: VP -> V ---
RULE_VP_INTRANS_LHS EQU 3
RULE_VP_INTRANS_LEN EQU 1
RULE_VP_INTRANS_0   EQU 2  ; V

; --- VP_ADV: VP -> V ADV ---
RULE_VP_ADV_LHS EQU 3
RULE_VP_ADV_LEN EQU 2
RULE_VP_ADV_0   EQU 2  ; V
RULE_VP_ADV_1   EQU 4  ; ADV

; --- VP_PREP: VP -> V PP ---
RULE_VP_PREP_LHS EQU 3
RULE_VP_PREP_LEN EQU 2
RULE_VP_PREP_0   EQU 2  ; V
RULE_VP_PREP_1   EQU 0  ; PP

; --- VP_NP_PP: VP -> V NP PP ---
RULE_VP_NP_PP_LHS EQU 3
RULE_VP_NP_PP_LEN EQU 3
RULE_VP_NP_PP_0   EQU 2  ; V
RULE_VP_NP_PP_1   EQU 0  ; NP
RULE_VP_NP_PP_2   EQU 0  ; PP

; --- VP_MODAL: VP -> MOD V ---
RULE_VP_MODAL_LHS EQU 3
RULE_VP_MODAL_LEN EQU 2
RULE_VP_MODAL_0   EQU 17  ; MOD
RULE_VP_MODAL_1   EQU 2  ; V

; --- VP_MODAL_NP: VP -> MOD V NP ---
RULE_VP_MODAL_NP_LHS EQU 3
RULE_VP_MODAL_NP_LEN EQU 3
RULE_VP_MODAL_NP_0   EQU 17  ; MOD
RULE_VP_MODAL_NP_1   EQU 2  ; V
RULE_VP_MODAL_NP_2   EQU 0  ; NP

; --- PP_BASIC: PP -> PRP NP ---
RULE_PP_BASIC_LHS EQU 4
RULE_PP_BASIC_LEN EQU 2
RULE_PP_BASIC_0   EQU 6  ; PRP
RULE_PP_BASIC_1   EQU 0  ; NP

; --- ADJP_BASIC: ADJP -> ADJ ---
RULE_ADJP_BASIC_LHS EQU 5
RULE_ADJP_BASIC_LEN EQU 1
RULE_ADJP_BASIC_0   EQU 3  ; ADJ

; --- ADJP_ADV: ADJP -> ADV ADJ ---
RULE_ADJP_ADV_LHS EQU 5
RULE_ADJP_ADV_LEN EQU 2
RULE_ADJP_ADV_0   EQU 4  ; ADV
RULE_ADJP_ADV_1   EQU 3  ; ADJ

; --- ADVP_BASIC: ADVP -> ADV ---
RULE_ADVP_BASIC_LHS EQU 6
RULE_ADVP_BASIC_LEN EQU 1
RULE_ADVP_BASIC_0   EQU 4  ; ADV

; --- ADVP_PREP: ADVP -> PRP NP ---
RULE_ADVP_PREP_LHS EQU 6
RULE_ADVP_PREP_LEN EQU 2
RULE_ADVP_PREP_0   EQU 6  ; PRP
RULE_ADVP_PREP_1   EQU 0  ; NP

